export { AuthModule } from './auth.module.js';
export { BearerAuthGuard } from './bearer-auth.guard.js';
export { RolesGuard } from './roles.guard.js';
export { IdentityGuard } from './identity.guard.js';
export { Roles, ROLES_KEY } from './roles.decorator.js';
export { Identities, IDENTITIES_KEY, type IdentitySpec } from './identities.decorator.js';
export { IdentityRegistry, type AuthenticatedUser, type IdentityName, type RoleName } from './identity-registry.js';
export { IDENTITY_SCOPES } from './identity-scopes.js';
export { RouteWalkerService } from './route-walker.service.js';
export { AUDITED_KEY } from './audited-key.js';
export { AppThrottlerModule } from './app-throttler.module.js';
export { AppThrottlerGuard } from './app-throttler-guard.js';
